name: 'Test Coverage'
on:
  pull_request:
    branches:
      - main
jobs:
  artiom-tr-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: artiomtr/jest-coverage-report-action@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80  # Min code coverage
          test_script: npm run coverage:format

  mattallty-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: npm run test
